### ISSUE TITLE
Warning message causes failure

### ISSUE THREAD

**Issue by keviny22** [retr0h/cookbook-parted#20]
Working on RHEL6u5, in some cases when calling resource that issues the parted command, if the command returns the below warning then fails the chef run. The only way i think we could work through this is to set `returns [0,1]` in the provider.  @retr0h what do you think about that approach?

```WARNING: the kernel failed to re-read the partition table on /dev/xvdj (Device or resource busy).  As a result, it may not reflect all of your changes until after reboot.```

**Comment by retr0h** [comment]
Closing, no updates.
